services:
  - name: leaked-passwords-api
    github_repo: GoodbyePlanet/leaked-passwords-api
    github_ref: main
    languages: [go]
    include:
      - "**/*.go"
      - "Dockerfile"
      - "go.mod"
      - "Makefile"
      - "README.md"
    exclude:

  - name: passkey-service
    github_repo: GoodbyePlanet/passkey-service
    github_ref: main
    languages: [go]
    include:
      - "**/*.go"
      - "Dockerfile"
      - "go.mod"
      - "docker-compose.yaml"
      - "Makefile"
      - "README.md"
    exclude:

  - name: auth-server
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    languages: [java]
    include:
      - "auth-server/src/main/java/**/*.java"
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: gateway
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    languages: [java]
    include:
      - "gateway/src/main/java/**/*.java"
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: secure-service
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    languages: [java]
    include:
      - "secure-service/src/main/java/**/*.java"
    exclude:
      - "**/test/**"
      - "**/target/**"

  - name: spring-cg-bff
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    languages: []
    include:
      - "docker-compose.yml"
      - "README.md"
    exclude:

  - name: fe-client
    github_repo: GoodbyePlanet/spring-cg-bff
    github_ref: main
    languages: [typescript]
    include:
      - "fe-client/src/**/*.ts"
      - "fe-client/src/**/*.tsx"
    exclude:
      - "**/node_modules/**"
