from __future__ import annotations

from mcp.server.fastmcp import FastMCP


def register_system_prompts(mcp: FastMCP) -> None:
    @mcp.prompt(
        name="system_design_overview",
        description="Produce a complete architectural overview of the whole system: service inventory,"
        " architectural layers, communication topology, shared data stores, cross-cutting concerns,"
        " and business domain mapping.",
    )
    def system_design_overview() -> str:
        """Complete system design overview across all indexed services."""
        return (
            "Produce a complete system design overview using the semcode MCP tools. "
            "Work through these steps:\n"
            "\n"
            "1. **Discover the service inventory.** Call `list_indexed_services` to get "
            "the full list. If nothing is indexed, stop and tell the user.\n"
            "\n"
            "2. **Detect architectural layers across services.** For every indexed service, "
            "call `find_symbol` or `search_code` with `symbol_type` values that reveal "
            "layering: `controller`, `repository`, `service`, `entity`, `config`, `mapper` "
            "(or equivalent language-specific types like `pydantic_model`, `api_route`, "
            "`struct`, `record`, `interface`). "
            "Build a per-service layer profile:\n"
            "   - **API layer** — controllers, handlers, routes, serializers\n"
            "   - **Service layer** — business logic, use cases, service classes\n"
            "   - **Data layer** — repositories, DAOs, entities, models\n"
            "   - **Config layer** — configuration classes, settings\n"
            "   - **DTO layer** — request/response objects, mappers\n"
            "   - **Middleware layer** — interceptors, filters, guards, auth\n"
            "   - **Utility layer** — helpers, shared logic, cross-cutting code\n"
            "Note which layers exist in each service and which symbols belong to each. "
            "Collect these per-service layer profiles for the output synthesis.\n"
            "\n"
            "3. **Profile each service.** For every service, invoke the `service_overview` "
            "prompt — it will identify entry points, domain types, architectural layers, "
            "and framework conventions for that service. Collect those summaries before "
            "proceeding.\n"
            "\n"
            "4. **Map inter-service communication.** Search across all services for "
            "outbound call patterns using queries like: "
            '`"http client"`, `"feign client"`, `"rest template"`, '
            '`"grpc stub"`, `"kafka producer"`, `"message publisher"`, '
            '`"event emitter"`, `"amqp"`. '
            "Build a dependency list noting which services are callers and which are "
            "called, and whether communication is synchronous or asynchronous.\n"
            "\n"
            "5. **Analyze dependency direction and layer violations.** For each "
            "inter-service dependency found in step 4, determine:\n"
            "   - **Direction** — does A depend on B, B depend on A, or both (cyclical)?\n"
            "   - **Caller layer** — which architectural layer (api, service, data) makes "
            "the outbound call? Call `find_usages` on the client/proxy class to find the "
            "caller's layer.\n"
            "   - **Layer boundary violations** — flag cases like a Controller in service A "
            "directly calling a Repository in service B (bypassing B's service layer), or "
            "circular dependencies between services.\n"
            "   - **Shared library detection** — if multiple services use the same client "
            "library or shared DTO package, note it.\n"
            "\n"
            "6. **Identify shared infrastructure.** Search for terms like "
            '`"datasource"`, `"redis"`, `"kafka"`, `"rabbitmq"`, `"s3"`, '
            '`"mongo"`, `"postgres"`, `"elasticsearch"` to surface data stores, '
            "caches, and message brokers. Note which services own vs. share each resource.\n"
            "\n"
            '7. **Find cross-cutting concerns.** Search for `"authentication"`, `"jwt"`, '
            '`"oauth"`, `"tracing"`, `"opentelemetry"`, `"metrics"`, '
            '`"circuit breaker"`, `"retry"`, `"rate limit"` to understand '
            "system-wide conventions.\n"
            "\n"
            "8. **Map business domains.** Group services by business function based on "
            "their purpose and communication patterns:\n"
            "   - Identify domain boundaries (e.g., ordering, payments, inventory, users, "
            "notifications)\n"
            "   - For each domain, list its constituent services and describe the "
            "domain's responsibility\n"
            "   - Trace a representative end-to-end flow for each domain: "
            "entry point → service orchestration → data access\n"
            "   - Note cross-domain interactions — which domains call which, and "
            "what data crosses domain boundaries\n"
            '   - Call `search_commits` with queries like `"new feature"`, '
            '`"domain"`, `"bounded context"` to find domain-relevant changes '
            "and understand evolution\n"
            "\n"
            "Then write the overview with these sections:\n"
            "\n"
            "- **System Purpose** — 2-3 sentences on what problem this collection of "
            "services solves as a whole.\n"
            "- **Service Inventory** — a table: Service | Purpose | Tech Stack | Entry Style.\n"
            "- **Architectural Layer Map** — a consolidated table across all services: "
            "Layer | Services Present In | Key Symbols. For each layer type (api, service, "
            "data, config, dto, middleware, utility), list which services have it and the "
            "main classes/symbols. Highlight any services that are missing an expected layer "
            "(e.g., a service with controllers but no explicit service layer).\n"
            "- **Communication Topology** — synchronous (REST/gRPC) vs asynchronous "
            "(events/queues) interactions. Include a dependency list: "
            "`ServiceA → ServiceB (REST)`, `ServiceC → broker → ServiceD (async)`, etc.\n"
            "- **Dependency Direction & Layer Boundaries** — for each inter-service link, "
            "state the direction and the caller's architectural layer. Flag any layer "
            "violations (e.g., cross-service data layer calls) or circular dependencies. "
            "Note which services use shared libraries.\n"
            "- **Data Architecture** — data stores, caches, and message brokers with "
            "ownership notes (owned by one service vs. shared).\n"
            "- **Cross-cutting Concerns** — how authentication, observability (tracing, "
            "metrics, logging), and resilience (retries, circuit breakers) are handled "
            "across the system.\n"
            "- **Key Architectural Patterns** — flag patterns you have evidence for: "
            "event-driven, CQRS, saga, API gateway, BFF, strangler fig, etc.\n"
            "- **Business Domain Architecture** — a domain map describing each business "
            "domain, its services, and cross-domain interactions. Include an "
            "end-to-end flow for at least one domain.\n"
            "- **Diagrams** — once the investigation is complete, render the findings as "
            "Mermaid diagrams in fenced ` ```mermaid ` code blocks:\n"
            "  - A **system context / component diagram** (`flowchart LR` or `graph LR`) "
            "showing every service, edge entry point, and data store as nodes; label "
            "edges with the protocol (REST, gRPC, async) and direction.\n"
            "  - A **data architecture diagram** (`flowchart` or `erDiagram`) showing "
            "which service owns which store and any sharing.\n"
            "  - If async messaging exists, add a **sequence diagram** "
            "(`sequenceDiagram`) for one representative end-to-end flow (e.g. a request "
            "that crosses multiple services or a key event chain).\n"
            "  - Optionally, add a **business domain diagram** (`flowchart LR`) showing "
            "domains as subgraphs with their services inside, and labeled edges for "
            "cross-domain interactions.\n"
            "  Only include diagrams for which you found concrete evidence in the code. "
            "Keep node labels short and consistent with the names used in the Service "
            "Inventory table.\n"
            "\n"
            "Skip any section (including diagrams) you have no evidence for. "
            "Do not invent details."
        )
